In [1]:
!pip install pandas numpy scikit-learn joblib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
from google.colab import files
files.upload()

Saving personal_transactions.csv to personal_transactions.csv

{'personal_transactions.csv': b"Date,Transaction Description,Amount,Transaction Type,Category,Account Name\r\n01-01-2018,Amazon,11.11,debit,Shopping,Platinum Card\r\n01-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n01-02-2018,Thai Restaurant,24.22,debit,Restaurants,Silver Card\r\n01-03-2018,Credit Card Payment,2298.09,credit,Credit Card Payment,Platinum Card\r\n01-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n01-05-2018,American Tavern,25.85,debit,Restaurants,Silver Card\r\n01-06-2018,Hardware Store,18.45,debit,Home Improvement,Silver Card\r\n01-08-2018,Gas Company,45,debit,Utilities,Checking\r\n01-08-2018,Hardware Store,15.38,debit,Home Improvement,Silver Card\r\n01-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n01-10-2018,Phone Company,89.46,debit,Mobile Phone,Checking\r\n01-11-2018,Shell,34.87,debit,Gas & Fuel,Platinum Card\r\n01-11-2018,Grocery Store,43.54,debit,Groceries,Platinum Card\r\n01-12-2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n01/13/2018,Pizza Place,32.91,debit,Fast Food,Platinum Card\r\n01/13/2018,Amazon,39.05,debit,Shopping,Platinum Card\r\n01/15/2018,Grocery Store,44.19,debit,Groceries,Silver Card\r\n01/15/2018,American Tavern,64.11,debit,Restaurants,Silver Card\r\n01/16/2018,City Water Charges,35,debit,Utilities,Checking\r\n01/16/2018,Power Company,60,debit,Utilities,Checking\r\n01/19/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n01/20/2018,Amazon,50.21,debit,Shopping,Platinum Card\r\n01/22/2018,Credit Card Payment,554.99,credit,Credit Card Payment,Platinum Card\r\n01/22/2018,Credit Card Payment,309.81,credit,Credit Card Payment,Silver Card\r\n01/22/2018,Credit Card Payment,554.99,debit,Credit Card Payment,Checking\r\n01/22/2018,Hardware Store,17.38,debit,Home Improvement,Silver Card\r\n01/23/2018,Credit Card Payment,309.81,debit,Credit Card Payment,Checking\r\n01/24/2018,Starbucks,3,debit,Coffee Shops,Platinum Card\r\n01/25/2018,Internet Service Provider,69.99,debit,Internet,Checking\r\n01/29/2018,Shell,30.42,debit,Gas & Fuel,Silver Card\r\n01/29/2018,Thai Restaurant,25,debit,Restaurants,Silver Card\r\n01/29/2018,Brunch Restaurant,17.62,debit,Restaurants,Platinum Card\r\n02-01-2018,Grocery Store,27.79,debit,Groceries,Platinum Card\r\n02-01-2018,Amazon,11.11,debit,Shopping,Platinum Card\r\n02-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n02-02-2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n02-03-2018,Japanese Restaurant,57.02,debit,Restaurants,Platinum Card\r\n02-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n02-05-2018,Credit Card Payment,145.14,credit,Credit Card Payment,Platinum Card\r\n02-06-2018,Credit Card Payment,154.13,credit,Credit Card Payment,Silver Card\r\n02-07-2018,Credit Card Payment,154.13,debit,Credit Card Payment,Checking\r\n02-07-2018,Gas Company,65,debit,Utilities,Checking\r\n02-09-2018,Barbershop,30,debit,Haircut,Platinum Card\r\n02-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n02-10-2018,Bojangles,10.66,debit,Fast Food,Platinum Card\r\n02-11-2018,Fancy Restaurant,106.8,debit,Restaurants,Platinum Card\r\n02-12-2018,Shell,36.47,debit,Gas & Fuel,Silver Card\r\n02-12-2018,Phone Company,89.52,debit,Mobile Phone,Checking\r\n02/14/2018,Brewing Company,14,debit,Alcohol & Bars,Silver Card\r\n02/15/2018,American Tavern,10,debit,Restaurants,Platinum Card\r\n02/15/2018,Power Company,60,debit,Utilities,Checking\r\n02/16/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n02/16/2018,Brunch Restaurant,8,debit,Restaurants,Silver Card\r\n02/16/2018,City Water Charges,35,debit,Utilities,Checking\r\n02/20/2018,Grocery Store,35.95,debit,Groceries,Silver Card\r\n02/20/2018,Mexican Restaurant,23.51,debit,Restaurants,Silver Card\r\n02/21/2018,Starbucks,2,debit,Coffee Shops,Platinum Card\r\n02/22/2018,Starbucks,4,debit,Coffee Shops,Silver Card\r\n02/26/2018,Credit Card Payment,765.37,credit,Credit Card Payment,Platinum Card\r\n02/26/2018,Credit Card Payment,156.11,credit,Credit Card Payment,Silver Card\r\n02/26/2018,Credit Card Payment,765.37,debit,Credit Card Payment,Checking\r\n02/26/2018,Internet Service Provider,74.99,debit,Internet,Checking\r\n02/26/2018,American Tavern,85.52,debit,Restaurants,Silver Card\r\n02/26/2018,Gas Station,32.21,debit,Gas & Fuel,Silver Card\r\n02/27/2018,Credit Card Payment,156.11,debit,Credit Card Payment,Checking\r\n03-01-2018,Grocery Store,32.07,debit,Groceries,Silver Card\r\n03-01-2018,Amazon,13.13,debit,Shopping,Platinum Card\r\n03-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n03-02-2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n03-03-2018,Grocery Store,23.74,debit,Groceries,Silver Card\r\n03-04-2018,Grocery Store,10.69,debit,Groceries,Platinum Card\r\n03-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n03-04-2018,BBQ Restaurant,42.24,debit,Restaurants,Platinum Card\r\n03-05-2018,Starbucks,3,debit,Coffee Shops,Platinum Card\r\n03-05-2018,Credit Card Payment,761.59,credit,Credit Card Payment,Silver Card\r\n03-05-2018,Credit Card Payment,761.59,debit,Credit Card Payment,Checking\r\n03-07-2018,Starbucks,3.5,debit,Coffee Shops,Platinum Card\r\n03-08-2018,BP,34.9,debit,Gas & Fuel,Platinum Card\r\n03-08-2018,Gas Company,52,debit,Utilities,Checking\r\n03-09-2018,Grocery Store,20.72,debit,Groceries,Platinum Card\r\n03-09-2018,Grocery Store,5.09,debit,Groceries,Platinum Card\r\n03-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n03-12-2018,Grocery Store,19.35,debit,Groceries,Platinum Card\r\n03-12-2018,Phone Company,89.52,debit,Mobile Phone,Checking\r\n03/13/2018,Amazon,45.75,debit,Shopping,Platinum Card\r\n03/14/2018,Grocery Store,22.5,debit,Groceries,Platinum Card\r\n03/14/2018,Brunch Restaurant,8.49,debit,Restaurants,Platinum Card\r\n03/15/2018,Starbucks,3.5,debit,Coffee Shops,Platinum Card\r\n03/15/2018,Power Company,60,debit,Utilities,Checking\r\n03/16/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n03/17/2018,Brewing Company,19.5,debit,Alcohol & Bars,Silver Card\r\n03/17/2018,Pizza Place,23.34,debit,Fast Food,Platinum Card\r\n03/19/2018,Mediterranean Restaurant,36.48,debit,Restaurants,Silver Card\r\n03/19/2018,City Water Charges,35,debit,Utilities,Checking\r\n03/20/2018,Amazon,14.97,debit,Shopping,Platinum Card\r\n03/22/2018,BP,30.55,debit,Gas & Fuel,Silver Card\r\n03/23/2018,Credit Card Payment,559.91,credit,Credit Card Payment,Platinum Card\r\n03/23/2018,Credit Card Payment,559.91,debit,Credit Card Payment,Checking\r\n03/23/2018,Grocery Store,11.76,debit,Groceries,Silver Card\r\n03/26/2018,Internet Service Provider,74.99,debit,Internet,Checking\r\n03/28/2018,Grocery Store,16.06,debit,Groceries,Silver Card\r\n03/28/2018,Pizza Place,24.98,debit,Restaurants,Silver Card\r\n03/29/2018,Steakhouse,17.64,debit,Restaurants,Silver Card\r\n03/30/2018,Grocery Store,9.09,debit,Groceries,Silver Card\r\n03/30/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n03/31/2018,Belgian Restaurant,38.32,debit,Restaurants,Platinum Card\r\n03/31/2018,Chili's,24.74,debit,Restaurants,Platinum Card\r\n03/31/2018,Greek Restaurant,41.16,debit,Restaurants,Silver Card\r\n04-01-2018,Grocery Store,80.79,debit,Groceries,Platinum Card\r\n04-01-2018,Brewing Company,59.48,debit,Restaurants,Platinum Card\r\n04-01-2018,Amazon,13.13,debit,Shopping,Platinum Card\r\n04-02-2018,Credit Card Payment,817.14,credit,Credit Card Payment,Silver Card\r\n04-02-2018,Credit Card Payment,817.14,debit,Credit Card Payment,Checking\r\n04-02-2018,Grocery Store,82.36,debit,Groceries,Platinum Card\r\n04-02-2018,Hardware Store,13.89,debit,Home Improvement,Platinum Card\r\n04-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n04-03-2018,Amazon Video,6.41,debit,Movies & DVDs,Platinum Card\r\n04-04-2018,Credit Card Payment,363.08,credit,Credit Card Payment,Platinum Card\r\n04-04-2018,Credit Card Payment,363.08,debit,Credit Card Payment,Checking\r\n04-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n04-06-2018,Chevron,4.58,debit,Gas & Fuel,Platinum Card\r\n04-06-2018,Tiny Deli,9.76,debit,Restaurants,Platinum Card\r\n04-08-2018,Irish Pub,22,debit,Restaurants,Platinum Card\r\n04-09-2018,Blue Sky Market,6.48,debit,Groceries,Silver Card\r\n04-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n04-09-2018,Gas Company,30,debit,Utilities,Checking\r\n04-11-2018,Phone Company,89.52,debit,Mobile Phone,Checking\r\n04-12-2018,Starbucks,7,debit,Coffee Shops,Platinum Card\r\n04-12-2018,Barbershop,30,debit,Haircut,Platinum Card\r\n04/13/2018,BP,37.98,debit,Gas & Fuel,Platinum Card\r\n04/13/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n04/13/2018,American Tavern,10.66,debit,Restaurants,Platinum Card\r\n04/14/2018,Hardware Store,11.61,debit,Home Improvement,Platinum Card\r\n04/14/2018,American Tavern,41,debit,Restaurants,Platinum Card\r\n04/16/2018,State Farm,75,debit,Auto Insurance,Checking\r\n04/16/2018,City Water Charges,35,debit,Utilities,Checking\r\n04/18/2018,Power Company,60,debit,Utilities,Checking\r\n04/20/2018,Thai Restaurant,24.22,debit,Restaurants,Silver Card\r\n04/21/2018,Grocery Store,4.32,debit,Groceries,Silver Card\r\n04/21/2018,American Tavern,35.15,debit,Restaurants,Silver Card\r\n04/22/2018,Grocery Store,21.32,debit,Groceries,Platinum Card\r\n04/23/2018,Hardware Store,42.7,debit,Home Improvement,Silver Card\r\n04/24/2018,Hardware Store,224.7,debit,Home Improvement,Platinum Card\r\n04/24/2018,Amazon,41.34,debit,Shopping,Platinum Card\r\n04/25/2018,Hardware Store,210.79,debit,Home Improvement,Silver Card\r\n04/25/2018,Internet Service Provider,74.99,debit,Internet,Checking\r\n04/26/2018,Credit Card Payment,769.72,credit,Credit Card Payment,Silver Card\r\n04/26/2018,Credit Card Payment,1216.94,credit,Credit Card Payment,Platinum Card\r\n04/26/2018,Credit Card Payment,1216.94,debit,Credit Card Payment,Checking\r\n04/27/2018,Credit Card Payment,769.72,debit,Credit Card Payment,Checking\r\n04/27/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n04/28/2018,Grocery Store,22.98,debit,Groceries,Silver Card\r\n04/29/2018,QuikTrip,39,debit,Gas & Fuel,Platinum Card\r\n04/29/2018,Grocery Store,51.05,debit,Groceries,Platinum Card\r\n04/29/2018,Hardware Store,68.47,debit,Home Improvement,Platinum Card\r\n04/30/2018,Grocery Store,5.09,debit,Groceries,Platinum Card\r\n05-01-2018,Amazon,13.13,debit,Shopping,Platinum Card\r\n05-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n05-03-2018,Amazon,49.72,debit,Shopping,Platinum Card\r\n05-04-2018,Grocery Store,42.23,debit,Groceries,Platinum Card\r\n05-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n05-05-2018,Bojangles,7.27,debit,Fast Food,Platinum Card\r\n05-05-2018,Pizza Place,20.52,debit,Fast Food,Platinum Card\r\n05-06-2018,Hardware Store,22.37,debit,Home Improvement,Platinum Card\r\n05-06-2018,Amazon,117.69,debit,Shopping,Platinum Card\r\n05-09-2018,Credit Card Payment,601.4,credit,Credit Card Payment,Platinum Card\r\n05-09-2018,Credit Card Payment,601.4,debit,Credit Card Payment,Checking\r\n05-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n05-09-2018,Gas Company,30,debit,Utilities,Checking\r\n05-10-2018,Phone Company,111.18,debit,Mobile Phone,Checking\r\n05-11-2018,Grocery Store,57.32,debit,Groceries,Platinum Card\r\n05-11-2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n05-11-2018,Mike's Construction Co.,8000,debit,Home Improvement,Checking\r\n05-12-2018,Liquor Store,27.77,debit,Alcohol & Bars,Platinum Card\r\n05-12-2018,Shell,33.3,debit,Gas & Fuel,Platinum Card\r\n05-12-2018,Fancy Restaurant,78,debit,Restaurants,Platinum Card\r\n05/14/2018,Grocery Store,67.63,debit,Groceries,Silver Card\r\n05/15/2018,Power Company,60,debit,Utilities,Checking\r\n05/17/2018,Barbershop,29,debit,Haircut,Silver Card\r\n05/17/2018,City Water Charges,35,debit,Utilities,Checking\r\n05/18/2018,State Farm,75,debit,Auto Insurance,Checking\r\n05/18/2018,Amazon,6.41,debit,Shopping,Platinum Card\r\n05/19/2018,Credit Card Payment,207.08,credit,Credit Card Payment,Platinum Card\r\n05/19/2018,Grocery Store,31,debit,Groceries,Silver Card\r\n05/19/2018,Greek Restaurant,23.26,debit,Restaurants,Silver Card\r\n05/21/2018,Credit Card Payment,283.07,credit,Credit Card Payment,Silver Card\r\n05/21/2018,Thai Restaurant,26.04,debit,Restaurants,Silver Card\r\n05/21/2018,Amazon,32.5,debit,Shopping,Platinum Card\r\n05/22/2018,Credit Card Payment,283.07,debit,Credit Card Payment,Checking\r\n05/24/2018,BP,39.44,debit,Gas & Fuel,Silver Card\r\n05/25/2018,Internet Service Provider,74.99,debit,Internet,Checking\r\n05/25/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n05/28/2018,Movie Theater,9.62,debit,Entertainment,Silver Card\r\n05/28/2018,Grocery Store,91.03,debit,Groceries,Silver Card\r\n05/29/2018,Movie Theater,20,debit,Movies & DVDs,Silver Card\r\n05/29/2018,Movie Theater,6.25,debit,Movies & DVDs,Silver Card\r\n06-01-2018,BP,38.63,debit,Gas & Fuel,Platinum Card\r\n06-01-2018,Grocery Store,6.11,debit,Groceries,Platinum Card\r\n06-01-2018,Amazon,13.13,debit,Shopping,Platinum Card\r\n06-02-2018,Credit Card Payment,235.18,credit,Credit Card Payment,Silver Card\r\n06-02-2018,Credit Card Payment,466.36,credit,Credit Card Payment,Platinum Card\r\n06-03-2018,Italian Restaurant,65.81,debit,Restaurants,Platinum Card\r\n06-04-2018,Credit Card Payment,235.18,debit,Credit Card Payment,Checking\r\n06-04-2018,Grocery Store,24.12,debit,Groceries,Platinum Card\r\n06-04-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n06-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n06-06-2018,Starbucks,4,debit,Coffee Shops,Platinum Card\r\n06-08-2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n06-08-2018,Gas Company,30,debit,Utilities,Checking\r\n06-09-2018,Chick-Fil-A,16.18,debit,Fast Food,Platinum Card\r\n06-09-2018,Grocery Store,9.56,debit,Groceries,Platinum Card\r\n06-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n06-10-2018,Grocery Store,46.01,debit,Groceries,Platinum Card\r\n06-12-2018,Grocery Store,12.55,debit,Groceries,Platinum Card\r\n06-12-2018,Phone Company,89.46,debit,Mobile Phone,Checking\r\n06/14/2018,Credit Card Payment,283.44,credit,Credit Card Payment,Platinum Card\r\n06/14/2018,Credit Card Payment,283.44,debit,Credit Card Payment,Checking\r\n06/14/2018,Grocery Store,7.02,debit,Groceries,Platinum Card\r\n06/15/2018,Power Company,60,debit,Utilities,Checking\r\n06/16/2018,Starbucks,3,debit,Coffee Shops,Platinum Card\r\n06/16/2018,Pizza Place,22.66,debit,Fast Food,Platinum Card\r\n06/16/2018,Grocery Store,13.9,debit,Groceries,Platinum Card\r\n06/18/2018,City Water Charges,35,debit,Utilities,Checking\r\n06/19/2018,Shell,38.52,debit,Gas & Fuel,Platinum Card\r\n06/19/2018,Grocery Store,2.69,debit,Groceries,Platinum Card\r\n06/20/2018,State Farm,75,debit,Auto Insurance,Checking\r\n06/20/2018,Credit Card Payment,89.45,credit,Credit Card Payment,Silver Card\r\n06/20/2018,Barbershop,30,debit,Haircut,Silver Card\r\n06/21/2018,Credit Card Payment,89.45,debit,Credit Card Payment,Checking\r\n06/22/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n06/23/2018,Brunch Restaurant,8.5,debit,Restaurants,Silver Card\r\n06/23/2018,Amazon,74.97,debit,Shopping,Platinum Card\r\n06/25/2018,Credit Card Payment,942.76,credit,Credit Card Payment,Platinum Card\r\n06/25/2018,Credit Card Payment,942.76,debit,Credit Card Payment,Checking\r\n06/25/2018,Internet Service Provider,74.99,debit,Internet,Checking\r\n06/26/2018,Grocery Store,9.62,debit,Groceries,Silver Card\r\n06/27/2018,Starbucks,3.5,debit,Coffee Shops,Silver Card\r\n06/27/2018,Pizza Place,22.66,debit,Fast Food,Platinum Card\r\n06/28/2018,Grocery Store,7.57,debit,Groceries,Silver Card\r\n07-01-2018,Amazon,13.13,debit,Shopping,Platinum Card\r\n07-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n07-02-2018,Movie Theater,25,debit,Movies & DVDs,Silver Card\r\n07-02-2018,American Tavern,36.44,debit,Restaurants,Silver Card\r\n07-04-2018,BP,34.48,debit,Gas & Fuel,Silver Card\r\n07-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n07-05-2018,Grocery Store,44.25,debit,Groceries,Silver Card\r\n07-05-2018,Amazon,212.32,debit,Shopping,Platinum Card\r\n07-06-2018,Amazon Video,6.41,debit,Movies & DVDs,Platinum Card\r\n07-06-2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n07-08-2018,Credit Card Payment,259.87,credit,Credit Card Payment,Platinum Card\r\n07-09-2018,Credit Card Payment,242.16,credit,Credit Card Payment,Silver Card\r\n07-09-2018,Credit Card Payment,259.87,debit,Credit Card Payment,Checking\r\n07-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n07-10-2018,Credit Card Payment,242.16,debit,Credit Card Payment,Checking\r\n07-10-2018,Grocery Store,5.39,debit,Groceries,Silver Card\r\n07-10-2018,Gas Company,30,debit,Utilities,Checking\r\n07-11-2018,Phone Company,89.46,debit,Mobile Phone,Checking\r\n07/14/2018,Go Mart,33.51,debit,Gas & Fuel,Silver Card\r\n07/15/2018,Circle K,36.24,debit,Gas & Fuel,Platinum Card\r\n07/17/2018,Wendy's,15.23,debit,Fast Food,Silver Card\r\n07/17/2018,City Water Charges,35,debit,Utilities,Checking\r\n07/17/2018,Power Company,60,debit,Utilities,Checking\r\n07/18/2018,Irish Restaurant,28.54,debit,Alcohol & Bars,Platinum Card\r\n07/18/2018,State Farm,75,debit,Auto Insurance,Checking\r\n07/20/2018,Credit Card Payment,61.43,credit,Credit Card Payment,Silver Card\r\n07/20/2018,Credit Card Payment,102.88,credit,Credit Card Payment,Platinum Card\r\n07/20/2018,Credit Card Payment,102.88,debit,Credit Card Payment,Checking\r\n07/20/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n07/21/2018,Grocery Store,28.93,debit,Groceries,Platinum Card\r\n07/21/2018,Barbershop,30,debit,Haircut,Platinum Card\r\n07/23/2018,Credit Card Payment,61.43,debit,Credit Card Payment,Checking\r\n07/23/2018,Starbucks,9.58,debit,Fast Food,Platinum Card\r\n07/24/2018,American Tavern,26.59,debit,Restaurants,Platinum Card\r\n07/25/2018,Internet Service Provider,74.99,debit,Internet,Checking\r\n07/26/2018,Conoco,33.67,debit,Gas & Fuel,Silver Card\r\n07/28/2018,Grocery Store,7.61,debit,Groceries,Silver Card\r\n07/30/2018,American Tavern,34.38,debit,Restaurants,Silver Card\r\n07/31/2018,Brewing Company,6.6,debit,Alcohol & Bars,Silver Card\r\n08-01-2018,Amazon,13.13,debit,Shopping,Platinum Card\r\n08-02-2018,Credit Card Payment,816.27,credit,Credit Card Payment,Platinum Card\r\n08-02-2018,Shell,40.44,debit,Gas & Fuel,Silver Card\r\n08-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking\r\n08-03-2018,Grocery Store,6.27,debit,Groceries,Silver Card\r\n08-03-2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n08-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card\r\n08-06-2018,Amazon,76.47,debit,Shopping,Platinum Card\r\n08-09-2018,Spotify,10.69,debit,Music,Platinum Card\r\n08-09-2018,Gas Company,30,debit,Utilities,Checking\r\n08-10-2018,Phone Company,89.4,debit,Mobile Phone,Checking\r\n08-11-2018,Chick-Fil-A,13.67,debit,Fast Food,Platinum Card\r\n08-11-2018,Valero,33.66,debit,Gas & Fuel,Platinum Card\r\n08/15/2018,Credit Card Payment,269.56,credit,Credit Card Payment,Silver Card\r\n08/15/2018,Credit Card Payment,159.38,credit,Credit Card Payment,Platinum Card\r\n08/15/2018,Shell,41.07,debit,Gas & Fuel,Platinum Card\r\n08/15/2018,Grocery Store,5.64,debit,Groceries,Platinum Card\r\n08/15/2018,Power Company,60,debit,Utilities,Checking\r\n08/16/2018,Credit Card Payment,269.56,debit,Credit Card Payment,Checking\r\n08/16/2018,City Water Charges,35,debit,Utilities,Checking\r\n08/17/2018,Biweekly Paycheck,2000,credit,Paycheck,Checking\r\n08/17/2018,Amazon,14.98,debit,Shopping,Platinum Card\r\n08/18/2018,Amazon,23.47,debit,Shopping,Platinum Card\r\n08/20/2018,State Farm,75,debit,Auto Insurance,Checking\r\n08/21/2018,Credit Card Payment,34.18,credit,Credit Card Payment,Silver Card\r\n08/21/2018,Credit Card Payment,99.76,credit,Credit Card Payment,Platinum Card\r\n08/21/2018,Credit Card Payment,99.76,debit,Credit Card Payment,Checking\r\n08/22/2018,Credit Card Payment,34.18,debit,Credit Card Payment,Checking\r\n08/24/2018,American Tavern,42.31,debit,Restaurants,Platinum Card\r\n08/27/2018,Internet Service Provid

In [3]:
import pandas as pd

df = pd.read_csv("personal_transactions.csv")
df.head()

,Date,Transaction Description,Amount,Transaction Type,Category,Account Name
0,01-01-2018,Amazon,11.11,debit,Shopping,Platinum Card
1,01-02-2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking
2,01-02-2018,Thai Restaurant,24.22,debit,Restaurants,Silver Card
3,01-03-2018,Credit Card Payment,2298.09,credit,Credit Card Payment,Platinum Card
4,01-04-2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card

In [6]:
X = df["Transaction Description"]
y = df["Category"]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1, 2)
    )),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [9]:
model.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(ngram_range=(1, 2), stop_words='english')),
                ('classifier', LogisticRegression(max_iter=1000))])

In [10]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

                        precision    recall  f1-score   support

        Alcohol & Bars       0.80      1.00      0.89         4
        Auto Insurance       1.00      1.00      1.00         3
          Coffee Shops       1.00      1.00      1.00         4
   Credit Card Payment       1.00      1.00      1.00        23
Electronics & Software       1.00      1.00      1.00         1
         Entertainment       0.00      0.00      0.00         1
             Fast Food       0.50      0.50      0.50         2
         Food & Dining       0.00      0.00      0.00         1
            Gas & Fuel       1.00      0.82      0.90        11
             Groceries       1.00      1.00      1.00        21
               Haircut       1.00      1.00      1.00         4
      Home Improvement       1.00      1.00      1.00         4
              Internet       1.00      1.00      1.00         4
          Mobile Phone       1.00      1.00      1.00         4
       Mortgage & Rent       1.00      1.00      1.00         4
         Movies & DVDs       0.50      0.80      0.62         5
                 Music       1.00      1.00      1.00         4
              Paycheck       1.00      1.00      1.00         7
           Restaurants       0.83      0.90      0.86        21
              Shopping       0.95      0.95      0.95        20
            Television       0.00      0.00      0.00         3
             Utilities       0.92      1.00      0.96        11

              accuracy                           0.93       162
             macro avg       0.80      0.82      0.80       162
          weighted avg       0.91      0.93      0.91       162

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [17]:
model.predict(["Amazon"])

array(['Shopping'], dtype=object)

In [12]:
import joblib

joblib.dump(model, "expense_classifier.pkl")

['expense_classifier.pkl']

In [13]:
files.download("expense_classifier.pkl")

In [20]:
test_cases = [
    "Starbucks",
    "Gas Company",
    "Netflix subscription",
    "Mortage Payment",
    "Power Company",
    "Grocery Store"
]

model.predict(test_cases)

array(['Coffee Shops', 'Utilities', 'Movies & DVDs',
       'Credit Card Payment', 'Utilities', 'Groceries'], dtype=object)

In [19]:
df["Category"].value_counts()

Category
Credit Card Payment       143
Groceries                 105
Restaurants                81
Utilities                  63
Shopping                   60
Gas & Fuel                 52
Paycheck                   46
Home Improvement           36
Coffee Shops               31
Alcohol & Bars             25
Internet                   21
Mortgage & Rent            21
Mobile Phone               21
Music                      21
Movies & DVDs              18
Auto Insurance             18
Fast Food                  16
Haircut                    13
Television                  8
Electronics & Software      4
Food & Dining               2
Entertainment               1
Name: count, dtype: int64